name: Display file content
run-name: file content

on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: write
  repository-projects: write      
jobs: 
  display_files:
    name: display file content
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      
      # Deliberate failure
      - name: cat file content
        # Inside task
        run: |
          cat test.txt
        shell: bash
      /*       
      - name: Create file content
        run: |
          echo "This is another test" >> test.txt
          git config --global user.email "nick.holbrook@gmail.com"
          git config --global user.name "Nick Holbrook"
          git add .
          git commit -am "Added another line"
          git status
          git remote -v
          git push origin main
        shell: bash     
        */

