name: Display file content
run-name: file content

on:
  push:
    branches:
      - main
      
jobs: 
  display_files:
    name: display file content
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      
      # Deliberate failure
      - name: display file content
        # Inside task
        run: |
          cat test.txt
        shell: bash
        
      - name: display file content
        run: |
          cat test.txt
        shell: bash        
